$(document).ready(function()
{
    $("#web-content").load("../features/dashboard.html");
    $('#dashboard').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/dashboard.html");
        evt.preventDefault();
    });
    $('#issue-book').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/issue_book.html");
        evt.preventDefault();
    });
    $('#return-book').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/return_book.html");
        evt.preventDefault();
    });
    $('#remove-book').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/remove_book.html");
        evt.preventDefault();
    });
    $('#update-book').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/update_book.html");
        evt.preventDefault();
    });
    $('#view-book').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/view_books.html");
        evt.preventDefault();
    });
    $('#view-issue').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/view_issue_books.html");
        evt.preventDefault();
    });
    $('#view-return').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/view_return_books.html");
        evt.preventDefault();
    });
    $('#demand-list').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/demand_books.html");
        evt.preventDefault();
    });
    $('#return-alert').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/return_alert.html");
        evt.preventDefault();
    });
    $('#change-password').on('click',function(evt)
    {
        $("#web-content").empty();
        $("#web-content").load("../features/change_password.html");
        evt.preventDefault();
    });
});
